package com.markel.flowstate.core.data

import android.content.Context
import android.graphics.Bitmap
import android.graphics.ImageDecoder
import android.net.Uri
import androidx.core.content.FileProvider
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.nio.file.AtomicMoveNotSupportedException
import java.nio.file.Files
import java.nio.file.StandardCopyOption
import java.util.UUID
import javax.inject.Inject
import javax.inject.Singleton
import kotlin.math.max
import kotlin.math.roundToInt

class CompletionPhotoDraft internal constructor(
    val id: String,
    val file: File,
    val captureUri: Uri,
)

/**
 * Owns task-completion photos from capture/import until permanent storage.
 *
 * External URIs are decoded and re-encoded before use. Room stores only the
 * generated UUID filename, never a caller-controlled path or content URI.
 */
@Singleton
class TaskCompletionPhotoStore @Inject constructor(
    @ApplicationContext private val context: Context,
) {
    private val draftDirectory = File(context.cacheDir, DRAFT_DIRECTORY).apply { mkdirs() }
    private val photoDirectory = File(context.filesDir, PHOTO_DIRECTORY).apply { mkdirs() }

    fun createCameraDraft(): CompletionPhotoDraft {
        val id = newPhotoId()
        val file = validatedChild(draftDirectory, id)
        file.parentFile?.mkdirs()
        if (!file.exists()) file.createNewFile()
        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.completion-files",
            file,
        )
        return CompletionPhotoDraft(id = id, file = file, captureUri = uri)
    }

    suspend fun importFromUri(uri: Uri): CompletionPhotoDraft = withContext(Dispatchers.IO) {
        val id = newPhotoId()
        val target = validatedChild(draftDirectory, id)
        val source = ImageDecoder.createSource(context.contentResolver, uri)
        decodeAndWrite(source, target)
        CompletionPhotoDraft(
            id = id,
            file = target,
            captureUri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.completion-files",
                target,
            ),
        )
    }

    suspend fun normalizeCameraDraft(draft: CompletionPhotoDraft): CompletionPhotoDraft =
        withContext(Dispatchers.IO) {
            requireValidDraft(draft)
            val normalized = File(draft.file.parentFile, "${draft.id}.normalized")
            try {
                decodeAndWrite(ImageDecoder.createSource(draft.file), normalized)
                atomicMove(normalized, draft.file, replaceExisting = true)
                draft
            } catch (error: Throwable) {
                normalized.delete()
                throw error
            }
        }

    suspend fun promote(draft: CompletionPhotoDraft): String = withContext(Dispatchers.IO) {
        requireValidDraft(draft)
        require(draft.file.length() in 1..MAX_FILE_BYTES) { "Invalid completion photo size" }

        val destination = validatedChild(photoDirectory, draft.id)
        val partial = File(photoDirectory, "${draft.id}.part")
        if (destination.exists()) {
            require(
                destination.isFile &&
                    destination.length() in 1..MAX_FILE_BYTES &&
                    filesHaveSameContents(draft.file, destination),
            ) { "Completion photo already exists with different contents" }
            return@withContext draft.id
        }
        try {
            draft.file.inputStream().use { input ->
                FileOutputStream(partial).use { output ->
                    input.copyTo(output)
                    output.fd.sync()
                }
            }
            check(partial.length() in 1..MAX_FILE_BYTES) { "Invalid completion photo size" }
            atomicMove(partial, destination, replaceExisting = false)
            draft.id
        } catch (error: Throwable) {
            partial.delete()
            throw error
        }
    }

    fun deleteDraft(draft: CompletionPhotoDraft?) {
        if (draft == null) return
        runCatching {
            requireValidDraft(draft)
            draft.file.delete()
        }
    }

    fun deletePhoto(photoId: String?) {
        if (!isValidPhotoId(photoId)) return
        runCatching { validatedChild(photoDirectory, requireNotNull(photoId)).delete() }
    }

    fun resolvePhoto(photoId: String?): File? {
        if (!isValidPhotoId(photoId)) return null
        return validatedChild(photoDirectory, requireNotNull(photoId)).takeIf(File::isFile)
    }

    /**
     * Restores a normalized/imported draft after process recreation.
     *
     * Only an opaque UUID generated by this store is accepted. The URI is not
     * reconstructed because a restored draft is never launched again; it is
     * only previewed, promoted, or deleted inside the app.
     */
    fun restorePhotoDraft(photoId: String?): CompletionPhotoDraft? =
        restoreDraft(photoId)?.takeIf { it.file.length() in 1..MAX_FILE_BYTES }

    /**
     * Restores the output file of an in-flight camera contract. A zero-byte
     * file is valid until the Activity Result callback reports cancellation or
     * the camera finishes writing into it.
     */
    fun restoreCameraDraft(photoId: String?): CompletionPhotoDraft? = restoreDraft(photoId)

    private fun restoreDraft(photoId: String?): CompletionPhotoDraft? {
        if (!isValidPhotoId(photoId)) return null
        val id = requireNotNull(photoId)
        val file = validatedChild(draftDirectory, id).takeIf(File::isFile) ?: return null
        return CompletionPhotoDraft(id = id, file = file, captureUri = Uri.EMPTY)
    }

    private fun requireValidDraft(draft: CompletionPhotoDraft) {
        require(isValidPhotoId(draft.id)) { "Invalid draft id" }
        val expected = validatedChild(draftDirectory, draft.id)
        require(expected.canonicalFile == draft.file.canonicalFile) { "Draft is outside private storage" }
        require(draft.file.isFile) { "Draft photo is missing" }
    }

    private fun decodeAndWrite(source: ImageDecoder.Source, target: File) {
        val partial = File(target.parentFile, "${target.name}.part")
        try {
            val bitmap = ImageDecoder.decodeBitmap(source) { decoder, info, _ ->
                val width = info.size.width
                val height = info.size.height
                require(width > 0 && height > 0) { "Invalid image dimensions" }
                val longest = max(width, height)
                if (longest > MAX_IMAGE_EDGE) {
                    val scale = MAX_IMAGE_EDGE.toFloat() / longest.toFloat()
                    decoder.setTargetSize(
                        (width * scale).roundToInt().coerceAtLeast(1),
                        (height * scale).roundToInt().coerceAtLeast(1),
                    )
                }
                decoder.allocator = ImageDecoder.ALLOCATOR_SOFTWARE
                decoder.memorySizePolicy = ImageDecoder.MEMORY_POLICY_LOW_RAM
            }
            check(bitmap.byteCount <= MAX_BITMAP_BYTES) { "Image is too large" }
            FileOutputStream(partial).use { output ->
                check(bitmap.compress(Bitmap.CompressFormat.JPEG, JPEG_QUALITY, output)) {
                    "Unable to encode completion photo"
                }
                output.fd.sync()
            }
            bitmap.recycle()
            check(partial.length() in 1..MAX_FILE_BYTES) { "Encoded image is too large" }
            atomicMove(partial, target, replaceExisting = true)
        } catch (error: Throwable) {
            partial.delete()
            target.delete()
            throw error
        }
    }

    private fun validatedChild(parent: File, name: String): File {
        require(isValidPhotoId(name) || name.endsWith(".normalized")) { "Invalid file name" }
        val child = File(parent, name).canonicalFile
        require(child.parentFile == parent.canonicalFile) { "Path escapes private storage" }
        return child
    }

    private fun atomicMove(source: File, destination: File, replaceExisting: Boolean) {
        val options = buildList {
            add(StandardCopyOption.ATOMIC_MOVE)
            if (replaceExisting) add(StandardCopyOption.REPLACE_EXISTING)
        }.toTypedArray()
        try {
            Files.move(source.toPath(), destination.toPath(), *options)
        } catch (_: AtomicMoveNotSupportedException) {
            val fallback = if (replaceExisting) {
                arrayOf(StandardCopyOption.REPLACE_EXISTING)
            } else {
                emptyArray()
            }
            Files.move(source.toPath(), destination.toPath(), *fallback)
        }
    }

    private fun filesHaveSameContents(first: File, second: File): Boolean {
        if (first.length() != second.length()) return false
        first.inputStream().buffered().use { firstInput ->
            second.inputStream().buffered().use { secondInput ->
                val firstBuffer = ByteArray(DEFAULT_BUFFER_SIZE)
                val secondBuffer = ByteArray(DEFAULT_BUFFER_SIZE)
                while (true) {
                    val firstRead = firstInput.read(firstBuffer)
                    val secondRead = secondInput.read(secondBuffer)
                    if (firstRead != secondRead) return false
                    if (firstRead == -1) return true
                    for (index in 0 until firstRead) {
                        if (firstBuffer[index] != secondBuffer[index]) return false
                    }
                }
            }
        }
    }

    private fun newPhotoId(): String = "${UUID.randomUUID()}.jpg"

    private fun isValidPhotoId(value: String?): Boolean =
        value != null && PHOTO_ID.matches(value)

    companion object {
        private const val DRAFT_DIRECTORY = "task_completion_drafts"
        private const val PHOTO_DIRECTORY = "task_completion_photos"
        private const val MAX_IMAGE_EDGE = 2048
        private const val MAX_BITMAP_BYTES = 20 * 1024 * 1024
        private const val MAX_FILE_BYTES = 12L * 1024L * 1024L
        private const val JPEG_QUALITY = 88
        private val PHOTO_ID = Regex(
            "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\\.jpg$",
        )
    }
}
